# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# branch to trigger on
trigger:
- master

# virtual machine image to use
pool:
  vmImage: 'Ubuntu-16.04'

# do series of steps
steps:

# download config file with credentials
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'config.js'

# copy to correct folder when building project
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.TempDirectory)
    contents: 'config.js' 
    targetFolder: 'src'

## install Node
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# install package dependencies
- script:
    npm install
  displayName: 'npm install'

# validate files
- script:
    grunt jshint
  displayName: 'Grunt jshint'

# run tests
- script:
    npm run test
  displayName: 'npm test'

# build project
- script:
    npm run build
  displayName: 'npm build'

# create artifact bundle
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'build' 
    includeRootFolder: false

# publish artifact to staging
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 